development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { "development_secret_key_base_#{Rails.application.class.module_parent_name.underscore}_#{Rails.env}_#{SecureRandom.hex(64)}" } %>

test:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { "test_secret_key_base_#{Rails.application.class.module_parent_name.underscore}_#{Rails.env}_#{SecureRandom.hex(64)}" } %>

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { "production_secret_key_base_#{Rails.application.class.module_parent_name.underscore}_#{Rails.env}_#{SecureRandom.hex(64)}" } %>
